# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 22:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCategory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PghHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('objectid', models.BigIntegerField()),
                ('fid_blockg', models.BigIntegerField()),
                ('statefp10', models.CharField(max_length=80)),
                ('countyfp10', models.CharField(max_length=80)),
                ('tractce10', models.CharField(max_length=80)),
                ('blkgrpce10', models.CharField(max_length=80)),
                ('geoid10', models.CharField(max_length=80)),
                ('namelsad10', models.CharField(max_length=80)),
                ('mtfcc10', models.CharField(max_length=80)),
                ('funcstat10', models.CharField(max_length=80)),
                ('aland10', models.BigIntegerField()),
                ('awater10', models.BigIntegerField()),
                ('intptlat10', models.CharField(max_length=80)),
                ('intptlon10', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('fid_neighb', models.BigIntegerField()),
                ('pghdbsdene', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('neighbor_field', models.BigIntegerField()),
                ('neighbor_i', models.BigIntegerField()),
                ('hood', models.CharField(max_length=80)),
                ('hood_no', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('sqmiles', models.FloatField()),
                ('dpwdiv', models.BigIntegerField()),
                ('unique_id', models.BigIntegerField()),
                ('sectors', models.BigIntegerField()),
                ('shape_le_1', models.FloatField()),
                ('shape_ar_1', models.FloatField()),
                ('page_numbe', models.CharField(max_length=80)),
                ('plannerass', models.CharField(max_length=80)),
                ('created_us', models.CharField(max_length=80)),
                ('created_da', models.CharField(max_length=80)),
                ('last_edite', models.CharField(max_length=80)),
                ('last_edi_1', models.CharField(max_length=80)),
                ('type', models.ForeignKey(default='pgh_hood', on_delete=django.db.models.deletion.CASCADE, to='geoservices.GeoCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
