# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geostuff.AdminRegion')),
                ('geo_id', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('tract', models.CharField(max_length=20)),
                ('lsad', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Census Tract',
                'verbose_name_plural': 'Census Tracts',
            },
            bases=('geostuff.adminregion',),
        ),
    ]
