# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pghhood',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
