# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostuff', '0003_censusblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geostuff.AdminRegion')),
                ('objectid', models.IntegerField()),
                ('district_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'School District',
                'verbose_name_plural': 'School Districts',
            },
            bases=('geostuff.adminregion',),
        ),
    ]
