# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0003_auto_20170426_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pghhood',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType'),
        ),
    ]
