# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geostuff', '0004_schooldistrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldistrict',
            old_name='objectid',
            new_name='object_id',
        ),
    ]
