# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0004_auto_20170426_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoCategory',
        ),
    ]
