# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 13:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0005_delete_geocategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACMunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=80)),
                ('cog', models.CharField(max_length=80)),
                ('schoold', models.CharField(max_length=80)),
                ('congdist', models.IntegerField()),
                ('fips', models.IntegerField()),
                ('region', models.CharField(max_length=80)),
                ('acres', models.FloatField()),
                ('sqmi', models.FloatField()),
                ('municode', models.CharField(max_length=80)),
                ('cntl_id', models.CharField(max_length=80)),
                ('cntycounci', models.IntegerField()),
                ('eoc', models.CharField(max_length=80)),
                ('assessorte', models.CharField(max_length=80)),
                ('valuationa', models.CharField(max_length=80)),
                ('yearconver', models.IntegerField()),
                ('globalid', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('pin', models.CharField(max_length=80)),
                ('mapblocklo', models.CharField(max_length=80)),
                ('shapearea', models.FloatField()),
                ('shapelen', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PghCityCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.BigIntegerField()),
                ('objectid', models.BigIntegerField()),
                ('intptlat10', models.CharField(max_length=80)),
                ('intptlon10', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('council', models.BigIntegerField()),
                ('councilman', models.CharField(max_length=80)),
                ('committee', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PghFireZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartodb_id', models.BigIntegerField()),
                ('firezones1', models.BigIntegerField()),
                ('firezones_field', models.BigIntegerField()),
                ('mapbook', models.CharField(max_length=80)),
                ('olddist_zo', models.CharField(max_length=80)),
                ('dist_zone', models.CharField(max_length=80)),
                ('shape_area', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('area', models.BigIntegerField()),
                ('dist', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PghPoliceZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('perimeter', models.FloatField()),
                ('zone', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PghPublicWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('pghdbsdedp', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('dpwdivs_field', models.BigIntegerField()),
                ('dpwdivs_id', models.BigIntegerField()),
                ('sqmiles', models.FloatField()),
                ('acres', models.FloatField()),
                ('division', models.BigIntegerField()),
                ('supervsr', models.CharField(max_length=80)),
                ('unique_id', models.BigIntegerField()),
                ('sq_miles', models.CharField(max_length=80)),
                ('dpw_divisi', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PghWard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('wards_field', models.BigIntegerField()),
                ('wards_id', models.BigIntegerField()),
                ('ward', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('sqmiles', models.FloatField()),
                ('unique_id', models.BigIntegerField()),
                ('council', models.BigIntegerField()),
                ('dpw_insp', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
