# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0006_acmunicipality_parcel_pghcitycouncil_pghfirezone_pghpolicezone_pghpublicworks_pghward'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmunicipality',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghcitycouncil',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghcitycouncil',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghcitycouncil',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType'),
        ),
        migrations.AddField(
            model_name='pghfirezone',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghfirezone',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghfirezone',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType'),
        ),
        migrations.AddField(
            model_name='pghpolicezone',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpolicezone',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpolicezone',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType'),
        ),
        migrations.AddField(
            model_name='pghpublicworks',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpublicworks',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpublicworks',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType'),
        ),
        migrations.AddField(
            model_name='pghward',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghward',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghward',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType'),
        ),
    ]
