# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostuff', '0006_auto_20180615_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='pghpublicworks',
            name='dpwdivs_field',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpublicworks',
            name='unique_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
