# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 16:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0008_auto_20170426_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geoservices.RegionType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='acmunicipality',
            options={'verbose_name': 'Allegheny County Municipality', 'verbose_name_plural': 'Allegheny County Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='pghcitycouncil',
            options={'verbose_name': 'Pittsburgh City Council District'},
        ),
        migrations.AlterModelOptions(
            name='pghfirezone',
            options={'verbose_name': 'Pittsburgh Fire Zone'},
        ),
        migrations.AlterModelOptions(
            name='pghhood',
            options={'verbose_name': 'Pittsburgh Neighborhood'},
        ),
        migrations.AlterModelOptions(
            name='pghpolicezone',
            options={'verbose_name': 'Pittsburgh Police Zone'},
        ),
        migrations.AlterModelOptions(
            name='pghpublicworks',
            options={'verbose_name': 'Pittsburgh DPW Division'},
        ),
        migrations.AlterModelOptions(
            name='pghward',
            options={'verbose_name': 'Pittsburgh Ward'},
        ),
        migrations.RenameField(
            model_name='acmunicipality',
            old_name='name',
            new_name='muni_name',
        ),
        migrations.RemoveField(
            model_name='acmunicipality',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='acmunicipality',
            name='id',
        ),
        migrations.RemoveField(
            model_name='acmunicipality',
            name='title',
        ),
        migrations.RemoveField(
            model_name='acmunicipality',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pghcitycouncil',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='pghcitycouncil',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pghcitycouncil',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pghcitycouncil',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pghcitycouncil',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pghfirezone',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='pghfirezone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pghfirezone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pghfirezone',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pghfirezone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pghhood',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='pghhood',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pghhood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pghhood',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pghhood',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pghpolicezone',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='pghpolicezone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pghpolicezone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pghpolicezone',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pghpolicezone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pghpublicworks',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='pghpublicworks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pghpublicworks',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pghpublicworks',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pghpublicworks',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pghward',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='pghward',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pghward',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pghward',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pghward',
            name='type',
        ),
        migrations.AddField(
            model_name='acmunicipality',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghcitycouncil',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghfirezone',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghhood',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpolicezone',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghpublicworks',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pghward',
            name='adminregion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion'),
            preserve_default=False,
        ),
    ]
