# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0011_auto_20170426_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='PghWard',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion')),
                ('fid', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('wards_field', models.BigIntegerField()),
                ('wards_id', models.BigIntegerField()),
                ('ward', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('sqmiles', models.FloatField()),
                ('unique_id', models.BigIntegerField()),
                ('council', models.BigIntegerField()),
                ('dpw_insp', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
            ],
            options={
                'verbose_name': 'Pittsburgh Ward',
            },
            bases=('geoservices.adminregion',),
        ),
        migrations.AlterUniqueTogether(
            name='adminregion',
            unique_together=set([]),
        ),
    ]
