# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0012_auto_20170426_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoservices.AdminRegion')),
                ('geo_id', models.IntegerField()),
                ('affgeoid', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('county', models.CharField(max_length=80)),
                ('tract', models.CharField(max_length=80)),
                ('block_grp', models.CharField(max_length=80)),
                ('cog', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Census Block Group',
                'verbose_name_plural': 'Allegheny County Municipalities',
            },
            bases=('geoservices.adminregion',),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='pin',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
