# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0013_auto_20170814_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockgroup',
            name='cog',
        ),
        migrations.AlterField(
            model_name='blockgroup',
            name='geo_id',
            field=models.CharField(max_length=20),
        ),
    ]
