# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0014_auto_20170814_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockgroup',
            options={'verbose_name': 'Census Block Group', 'verbose_name_plural': 'Census Block Groups'},
        ),
    ]
