# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0015_auto_20170814_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='addr_city',
            field=models.CharField(default='', max_length=20, verbose_name='address city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='addr_fraction',
            field=models.CharField(default='', max_length=20, verbose_name='address fraction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='addr_number',
            field=models.CharField(default='', max_length=20, verbose_name='address number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='addr_state',
            field=models.CharField(default='', max_length=20, verbose_name='address state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='addr_street',
            field=models.CharField(default='', max_length=20, verbose_name='address street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='addr_unit',
            field=models.CharField(default='', max_length=20, verbose_name='address unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='addr_zip',
            field=models.CharField(default='', max_length=20, verbose_name='address zip'),
            preserve_default=False,
        ),
    ]
