# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0017_auto_20170818_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='addr_city',
            field=models.CharField(max_length=40, verbose_name='address city'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='addr_street',
            field=models.CharField(max_length=40, verbose_name='address street'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='addr_zip',
            field=models.CharField(max_length=5, verbose_name='address zip'),
        ),
    ]
