# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0020_addresspoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresspoint',
            name='edit_date',
            field=models.CharField(max_length=30),
        ),
    ]
