# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0021_auto_20170829_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresspoint',
            old_name='objectid',
            new_name='object_id',
        ),
    ]
