# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0022_auto_20170829_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresspoint',
            name='object_id',
            field=models.IntegerField(max_length=60),
        ),
    ]
