# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0025_remove_addresspoint_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresspoint',
            name='source_id',
        ),
    ]
