# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0026_remove_addresspoint_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresspoint',
            name='comment',
            field=models.CharField(max_length=300),
        ),
    ]
