# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoservices', '0027_auto_20170829_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresspoint',
            name='city',
            field=models.CharField(default='', max_length=60, verbose_name='city used in address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresspoint',
            name='municipality',
            field=models.CharField(max_length=60, verbose_name='administrative region'),
        ),
    ]
